# Generated by Django 4.1.3 on 2023-02-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile_No', models.IntegerField()),
                ('Whatsapp_No', models.IntegerField()),
                ('Village', models.CharField(max_length=30)),
                ('District', models.CharField(max_length=30)),
                ('Pin_code', models.IntegerField()),
            ],
        ),
    ]
