# Generated by Django 4.1.3 on 2023-04-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0002_alter_farmer_mobile_no_alter_farmer_pin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='created_employee',
            field=models.CharField(default='mohit', max_length=50),
            preserve_default=False,
        ),
    ]
