# Generated by Django 4.1.3 on 2023-04-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0003_farmer_created_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='created_employee',
            field=models.CharField(max_length=100),
        ),
    ]
