# Generated by Django 4.1.3 on 2023-03-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_app', '0003_alter_dealer_gst_no_alter_dealer_pin_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributer',
            name='user',
        ),
        migrations.AddField(
            model_name='dealer',
            name='authorized_distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dealer_app.distributer'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='Address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='distributer',
            name='Address',
            field=models.TextField(max_length=100),
        ),
    ]
